version: '3'
services:
  backend:
    container_name: backend 
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - backend  
      - db 
    ports:
      - 4000:3000
    env_file:
      - .env   
  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - frontend     
    ports:
      - 8080:80
  my_bd:
    image: 'postgres'
    container_name: postgres
    volumes:
      - posgres_data:/data/postgres  
    networks:
      - db     
    env_file:
      - .env     
volumes:  
  posgres_data:

networks:
  backend:
  db:
  frontend: